import dogImage from "../../assets/images/dog.jpg";

/*
classWithScheduleDtos : [{
                classId : 1,
                name : "웹 / 앱",
                cohort : "2기",
                schedules: [            
                    id : 1,
                    subjectName : "웹 / 앱",
                    startDate : "2025-05-01",
                    endDate : "2025-10-31",
                    classDesc : "웹 / 앱 개발 클래스",
                    classUrl : "https://www.google.com"
                ]
}]

instructor : [{
                "email": "dwc071092@naver.com",
                "name": "오창은",
                "birth": "2025-06-23",
                "gender": "남성",
                "phone": "01012345678",
                "address": "",
                "profileImage": null,
                "classId": 5,
                "position": "강사"
}]
*/

const allClassFetch = async (token) => {
  const requestInit = {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  };
  console.log(import.meta.env.VITE_ORGANIZATION_API_URL);
  const url = new URL(`${import.meta.env.VITE_ORGANIZATION_API_URL}/init`);

  const response = await fetch(url, requestInit);

  if (200 <= response.status && response.status < 300) {
    const responseJson = await response.json();
    return responseJson.data;
  } else {
    const errorStatus = response.json().status;
    const errorMessage = response.json().message;
    throw new Error(`${errorStatus} : ${errorMessage}`);
  }
};

const singleClassFetch = async (id, token) => {
  const requestInit = {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  };
  const url = new URL(
    `${import.meta.env.VITE_ORGANIZATION_API_URL}/class/${id}`
  );

  const response = await fetch(url, requestInit);

  if (200 <= response.status && response.status < 300) {
    const responseJson = await response.json();
    return responseJson.data;
  } else {
    const errorStatus = response.json().status;
    const errorMessage = response.json().message;
    throw new Error(`${errorStatus} : ${errorMessage}`);
  }
};

export { allClassFetch, singleClassFetch };

const mockOnlyClassData = [
  {
    id: 1,
    name: "웹 / 앱",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "웹 / 앱 개발 클래스",
    instructor: {
      id: 1,
      name: "홍길동",
      email: "hong@gmail.com",
      phone_num: "010-1234-5678",
      profile_image: dogImage,
      birth: "1990-01-01",
      gender: "남자",
      address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
      is_active: true,
    },
  },
  {
    id: 2,
    name: "임베디드",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "임베디드 개발 클래스",
    instructor: {
      id: 1,
      name: "홍길동",
      email: "hong@gmail.com",
      phone_num: "010-1234-5678",
      profile_image: dogImage,
      birth: "1990-01-01",
      gender: "남자",
      address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
      is_active: true,
    },
  },
  {
    id: 3,
    name: "스마트팩토리",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "스마트팩토리 개발 클래스",
    instructor: {
      id: 1,
      name: "홍길동",
      email: "hong@gmail.com",
      phone_num: "010-1234-5678",
      profile_image: dogImage,
      birth: "1990-01-01",
      gender: "남자",
      address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
      is_active: true,
    },
  },
  {
    id: 4,
    name: "보안",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "보안 개발 클래스",
    instructor: {
      id: 1,
      name: "홍길동",
      email: "hong@gmail.com",
      phone_num: "010-1234-5678",
      profile_image: dogImage,
      birth: "1990-01-01",
      gender: "남자",
      address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
      is_active: true,
    },
  },
  {
    id: 5,
    name: "클라우드",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "클라우드 개발 클래스",
    instructor: {
      id: 1,
      name: "홍길동",
      email: "hong@gmail.com",
      phone_num: "010-1234-5678",
      profile_image: dogImage,
      birth: "1990-01-01",
      gender: "남자",
      address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
      is_active: true,
    },
  },
];

const mockClassData = [
  {
    id: 1,
    name: "웹 / 앱",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "웹 / 앱 개발 클래스",
    members: [
      {
        id: 1,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 2,
        name: "이순신",
        email: "lee@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 3,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 4,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 5,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 6,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 7,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 8,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 9,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 10,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 11,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 12,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 13,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 14,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 15,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 16,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 17,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 18,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 19,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 20,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 21,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 22,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 23,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 24,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 25,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
    ],
  },
  {
    id: 2,
    name: "임베디드",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "임베디드 개발 클래스",
    members: [
      {
        id: 1,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 2,
        name: "이순신",
        email: "lee@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 3,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 4,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 5,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 6,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 7,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 8,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 9,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 10,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 11,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 12,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 13,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 14,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 15,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 16,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 17,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 18,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 19,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 20,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 21,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 22,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 23,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 24,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 25,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
    ],
  },
  {
    id: 3,
    name: "스마트팩토리",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "스마트팩토리 개발 클래스",
    members: [
      {
        id: 1,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 2,
        name: "이순신",
        email: "lee@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 3,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 4,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 5,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 6,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 7,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 8,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 9,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 10,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 11,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 12,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 13,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 14,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 15,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 16,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 17,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 18,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 19,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 20,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 21,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 22,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 23,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 24,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 25,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
    ],
  },
  {
    id: 4,
    name: "보안",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "보안 개발 클래스",
    members: [
      {
        id: 1,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 2,
        name: "이순신",
        email: "lee@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 3,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 4,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 5,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 6,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 7,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 8,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 9,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 10,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 11,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 12,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 13,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 14,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 15,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 16,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 17,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 18,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 19,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 20,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 21,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 22,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 23,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 24,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 25,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
    ],
  },
  {
    id: 5,
    name: "클라우드",
    cohort: "2기",
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    classDesc: "클라우드 개발 클래스",
    members: [
      {
        id: 1,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 2,
        name: "이순신",
        email: "lee@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 3,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 4,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 5,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 6,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 7,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 8,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 9,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 10,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 11,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 12,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 13,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 14,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 15,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 16,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 17,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 18,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 19,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 20,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 21,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 22,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 23,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 24,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
      {
        id: 25,
        name: "홍길동",
        email: "hong@gmail.com",
        phone_num: "010-1234-5678",
        profile_image: dogImage,
        birth: "1990-01-01",
        gender: "남자",
        address: "서울특별시 강남구 테헤란로 14길 6 남도빌딩 2층 201호",
        is_active: true,
      },
    ],
  },
];
